dist: trusty
sudo: false

language: node_js
node_js:
  - "12"

addons:
  apt:
    sources:
      - sudo google-chrome
    packages:
      - sudu google-chrome-stable

cache:
  directories:
     - ./node_modules

before_install:
  - sudo apt-get update
  - sudo apt-get -y install libxml2-dev

install:
  - npm install

script:
  - npm run lint
  - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
  - npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
  - npm run build --prod --base-href https://hs950559.github.io/angular-testing-demo/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/ngtest
  on:
    branch: master
